# Generated by Django 4.0.2 on 2022-02-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='categry',
            new_name='category',
        ),
    ]
