# Generated by Django 4.0.2 on 2022-02-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_categry_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='idenfier',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
