# Generated by Django 4.0.2 on 2022-02-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_remove_usercreation_posts'),
        ('blog', '0004_remove_blog_idenfier_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='category',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Draft',
        ),
    ]
