# Generated by Django 4.0.2 on 2022-02-08 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_remove_usercreation_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCreation',
        ),
    ]
