# Generated by Django 4.0.2 on 2022-02-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCreation',
        ),
    ]
