# Generated by Django 4.0.2 on 2022-02-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_address_usercreation_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreation',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.address'),
        ),
    ]
