# Generated by Django 4.0.2 on 2022-02-08 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0009_alter_usercreation_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreation',
            name='address',
        ),
    ]
