# Generated by Django 4.0.2 on 2022-02-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0010_remove_usercreation_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='UserCreation',
        ),
    ]
