# Generated by Django 4.0.2 on 2022-02-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0013_address_usercreation_delete_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreation',
            name='pic',
            field=models.FileField(null=True, upload_to='uploads'),
        ),
    ]
