# Generated by Django 4.0.2 on 2022-02-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreation',
            name='pic',
            field=models.FileField(default='default.jpg', upload_to='uploads'),
        ),
    ]
