# Generated by Django 4.0.2 on 2022-02-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0017_alter_usercreation_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usercreation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='UserCreation',
        ),
    ]
