# Generated by Django 4.0.2 on 2022-02-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0020_alter_usercreation_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreation',
            name='pic',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
