# Generated by Django 4.0.2 on 2022-02-12 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('doctor', '0021_alter_usercreation_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreation',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog'),
        ),
    ]
