# Generated by Django 4.0.2 on 2022-02-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0022_usercreation_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreation',
            name='posts',
        ),
    ]
