# Generated by Django 4.0.2 on 2022-02-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_remove_usercreation_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreation',
            name='cal_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
